config/routes.rb
Rails.application.routes.draw do
  mount EpiCas::Engine, at: '/'
  devise_for :users
  resources :group_cads
  resources :attachment_builds
  resources :group_builds
  resources :group_machines
  resources :attachment_machines
  resources :builds
  resources :machine_parameters
  resources :parameters
  resources :machines do
    get :parameters, on: :member
  end
  resources :build_projects
  resources :group_materials
  resources :materials
  resources :cads
  resources :group_users
  resources :attachments
  resources :groups
  resources :users
  resources :profile

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'cads/:id/download', to: 'cads#download', as: 'download_cad'

  get 'materials/:id/download/:attribute', to: 'materials#download', as: 'download_material' # Defines the root path route ("/")

  get 'builds/id/:id/download', to: 'builds#download', as: 'download_build'

  root 'pages#home'
end

app/models/group_cad.rb
# == Schema Information
#
# Table name: group_cads
#
#  id         :bigint           not null, primary key
#  cadId      :integer
#  groupId    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Foreign Keys
#
#  fk_rails_...  (cadId => cads.id)
#  fk_rails_...  (groupId => groups.id)
#
class GroupCad < ApplicationRecord
  validates :cadId, uniqueness: { scope: :groupId, message: 'CAD already exists in group' }
  belongs_to :group, foreign_key: 'groupId'
  belongs_to :cad, foreign_key: 'cadId'
end

app/controllers/group_cads_controller.rb
class GroupCadsController < ApplicationController
  before_action :set_group_cad, only: %i[show edit update destroy]

  authorize_resource

  # GET /group_cads
  def index
    @group_cads = GroupCad.all
  end

  # GET /group_cads/1
  def show; end

  # GET /group_cads/new
  def new
    @group = Group.find(params[:format])

    # Show all group cads at the top
    @group_cads = @group.group_cads
    @group_cads = apply_word_filter(@group_cads, :name, params[:name], group_cads: true) if params[:name].present?

    # Show remaining cads
    @cads = Cad.all - @group_cads.map(&:cad)
    @cads = apply_word_filter(@cads, :name, params[:name]) if params[:name].present?
  end

  # GET /group_cads/1/edit
  def edit; end

  # POST /group_cads
  def create
    @group_cad = GroupCad.new(group_cad_params)
    @group = Group.find(params[:group_cad][:groupId])

    if @group_cad.save
      redirect_to new_group_cad_path(format: @group_cad.groupId), notice: 'CAD was successfully added to Group.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /group_cads/1
  def update
    if @group_cad.update(group_cad_params)
      redirect_to @group_cad, notice: 'Group cad was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /group_cads/1
  def destroy
    @group_cad.destroy
    redirect_to new_group_cad_path(@group_cad.group), notice: 'CAD was successfully removed from Group.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group_cad
    @group_cad = GroupCad.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_cad_params
    params.require(:group_cad).permit(:groupId, :cadId)
  end

  # Filter CADs
  def apply_word_filter(objects, attribute, value, group_cads: false)
    objects.select do |object|
      if group_cads
        object.cad.send(attribute).downcase.include?(value.downcase)
      else
        object.send(attribute).downcase.include?(value.downcase)
      end
    end
  end
end

app/views/group_cads/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@group_cad) do |f|
  .card-body
    .m-2
      = f.input :groupId, as: :hidden
      = f.label :groupName, 'Adding to group'
      = f.label @group.name, class: 'form-control', readonly: true
    .m-2
      = f.label :cadId, 'Select a CAD file'
      = f.collection_select :cadId, @cads, :id, :name, { prompt: 'Select a CAD file' }, class: 'form-control'

  .card-footer.d-flex
    %button.btn.btn-primary{ type: 'submit' }
      Save
    = link_to 'Back', edit_group_path(@group), class: 'btn btn-link ms-auto'

app/views/group_cads/edit.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header Editing Group Cad
      = render 'form'

app/views/group_cads/index.html.haml
.card
  .card-header.d-flex.align-items-center
    %span Listing Group Cads

    = link_to 'New Group cad', new_group_cad_path, class: 'btn btn-outline-secondary ms-auto'

  %table.table
    %thead
      %tr
        %th Groupid
        %th Cadid
        %th
    %tbody
      - @group_cads.each do |group_cad|
        %tr
          %td= group_cad.groupId
          %td= group_cad.cadId
          %td
            .btn-toolbar.float-end
              = link_to 'Show', group_cad, class: 'btn btn-outline-secondary btn-sm'
              = link_to 'Edit', edit_group_cad_path(group_cad), class: 'btn btn-outline-secondary ms-1 btn-sm'
              = link_to 'Destroy', group_cad, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger ms-1 btn-sm'

app/views/group_cads/new.html.haml
.card.mb-3
  .card-header.d-flex.align-items-center
    %span Add CAD to: #{@group.name}
    = link_to 'Back', edit_group_path(@group), class: 'btn btn-outline-secondary ms-auto'

  #filterOptions.show
    .card-body
      = form_tag request.fullpath, method: :get, class: 'd-flex flex-column px-3' do 
        .row
          .form-group.col-md-4.mb-2
            = label_tag :name, "File Name:"
            = text_field_tag :name, params[:name], class: 'form-control', placeholder: 'File Name'
        .justify-content-between
          = submit_tag "Search", class: 'btn btn-primary'
          = link_to "Clear", new_group_cad_path(@group), class: 'btn btn-secondary'
.card.mb-2
  %table.table.table-striped.table-hover
    %thead.table-secondary
      %tr
        %th 
          File name
          = link_to '▲', request.params.merge(sort: 'name', order: 'asc'), class: 'text-decoration-none text-primary'
          = link_to '▼', request.params.merge(sort: 'name', order: 'desc'), class: 'text-decoration-none text-primary'
        %th 
          File Type
          = link_to '▲', request.params.merge(sort: 'file_type', order: 'asc'), class: 'text-decoration-none text-primary'
          = link_to '▼', request.params.merge(sort: 'file_type', order: 'desc'), class: 'text-decoration-none text-primary'
        %th 
          Creator
          = link_to '▲', request.params.merge(sort: 'createdBy', order: 'asc'), class: 'text-decoration-none text-primary'
          = link_to '▼', request.params.merge(sort: 'createdBy', order: 'desc'), class: 'text-decoration-none text-primary'
        %th 
          Last Modifier
          = link_to '▲', request.params.merge(sort: 'modifiedBy', order: 'asc'), class: 'text-decoration-none text-primary'
          = link_to '▼', request.params.merge(sort: 'modifiedBy', order: 'desc'), class: 'text-decoration-none text-primary'
        %th
          Archived
        %th

    %tbody
      - @group_cads.each do |group_cad|
        %tr
          - cad = group_cad.cad
          %td= cad.name
          %td= cad.file_type
          %td= cad.created_by.email
          %td= cad.modified_by.email
          %td= cad.archived
          %td
            .btn-toolbar.float-end
              = button_to 'Remove', group_cad_path(group_cad),method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm'
      - @cads.each do |cad|
        %tr
          %td= cad.name
          %td= cad.file_type
          %td= cad.created_by.email
          %td= cad.modified_by.email
          %td= cad.archived
          %td
            .btn-toolbar.float-end
              = form_with url: group_cads_path, method: :post, scope: :group_cad do |form|
                = form.hidden_field :groupId, value: @group.id
                = form.hidden_field :cadId, value: cad.id
                = form.submit 'Add', class: 'btn btn-outline-secondary btn-sm'

app/views/group_cads/show.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header
        Group Cad details
      .card-body
        %dl.row.mb-0
          %dt.col-md-3 Groupid:
          %dd.col-md-9= @group_cad.groupId
          %dt.col-md-3 Cadid:
          %dd.col-md-9= @group_cad.cadId
      .card-footer.d-flex
        = link_to 'Edit', edit_group_cad_path(@group_cad), class: 'btn btn-link'
        = link_to 'Back', group_cads_path, class: 'btn btn-link ms-auto'