config/routes.rb
Rails.application.routes.draw do
  mount EpiCas::Engine, at: '/'
  devise_for :users
  resources :group_cads
  resources :attachment_builds
  resources :group_builds
  resources :group_machines
  resources :attachment_machines
  resources :builds
  resources :machine_parameters
  resources :parameters
  resources :machines do
    get :parameters, on: :member
  end
  resources :build_projects
  resources :group_materials
  resources :materials
  resources :cads
  resources :group_users
  resources :attachments
  resources :groups
  resources :users
  resources :profile

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'cads/:id/download', to: 'cads#download', as: 'download_cad'

  get 'materials/:id/download/:attribute', to: 'materials#download', as: 'download_material' # Defines the root path route ("/")

  get 'builds/id/:id/download', to: 'builds#download', as: 'download_build'

  root 'pages#home'
end

app/models/group_material.rb
# == Schema Information
#
# Table name: group_materials
#
#  id         :bigint           not null, primary key
#  groupId    :integer
#  materialId :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Foreign Keys
#
#  fk_rails_...  (groupId => groups.id)
#  fk_rails_...  (materialId => materials.id)
#
class GroupMaterial < ApplicationRecord
  validates :groupId, uniqueness: { scope: :materialId, message: 'Material already exists in group' }
  belongs_to :group, foreign_key: 'groupId'
  belongs_to :material, foreign_key: 'materialId'
end

app/controllers/group_materials_controller.rb
class GroupMaterialsController < ApplicationController
  before_action :set_group_material, only: %i[destroy]

  authorize_resource

  # GET /group_materials/new
  def new
    @group = Group.find(params[:format])

    # Show all group materials at the top
    @group_materials = @group.group_materials
    if params[:name].present?
      @group_materials = apply_word_filter(@group_materials, :name, params[:name],
                                           group_materials: true)
    end

    # Show remaining materials
    @materials = Material.all - @group_materials.map(&:material)
    @materials = apply_word_filter(@materials, :name, params[:name]) if params[:name].present?
  end

  # POST /group_materials
  def create
    @group_material = GroupMaterial.new(group_material_params)
    @group = Group.find(params[:group_material][:groupId])

    if @group_material.save
      redirect_to new_group_material_path(format: @group_material.groupId),
                  notice: 'Group material was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # DELETE /group_materials/1
  def destroy
    @group_material.destroy
    redirect_to new_group_material_path(@group_material.group), notice: 'Material was successfully removed from group.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group_material
    @group_material = GroupMaterial.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_material_params
    params.require(:group_material).permit(:groupId, :materialId)
  end

  # Applies a word filter to a collection of objects based on a specified attribute and value.
  def apply_word_filter(objects, attribute, value, group_materials: false)
    objects.select do |object|
      if group_materials
        object.material.send(attribute).downcase.include?(value.downcase)
      else
        object.send(attribute).downcase.include?(value.downcase)
      end
    end
  end

  def apply_sorting
    allowed_sort_columns = %w[name material_type meltingOnset crystallisationOnset created_at
                              updated_at modifiedBy createdBy]
    allowed_order_directions = %w[asc desc]

    if allowed_sort_columns.include?(params[:sort]) && allowed_order_directions.include?(params[:order].downcase)
      @materials = @materials.order("#{params[:sort]} #{params[:order]}")
    end
  end
end

app/views/group_materials/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@group_material) do |f|
  .card-body
    .m-2
      = f.input :groupId, as: :hidden
      = f.label :groupName, 'Adding to group'
      = f.label @group.name, class: 'form-control', readonly: true
    .m-2
      = f.label :materialId, 'Select a material'
      = f.collection_select :materialId, @materials, :id, :name, { prompt: 'Select a material' }, class: 'form-control'

  .card-footer.d-flex
    %button.btn.btn-primary{ type: 'submit' }
      Save
    = link_to 'Back', edit_group_path(@group), class: 'btn btn-link ms-auto'

app/views/group_materials/edit.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header Editing Group Material
      = render 'form'

app/views/group_materials/index.html.haml
.card
  .card-header.d-flex.align-items-center
    %span Listing Group Materials

    = link_to 'New Group material', new_group_material_path, class: 'btn btn-outline-secondary ms-auto'

  %table.table
    %thead
      %tr
        %th Groupid
        %th Materialid
        %th
    %tbody
      - @group_materials.each do |group_material|
        %tr
          %td= group_material.groupId
          %td= group_material.materialId
          %td
            .btn-toolbar.float-end
              = link_to 'Show', group_material, class: 'btn btn-outline-secondary btn-sm'
              = link_to 'Edit', edit_group_material_path(group_material), class: 'btn btn-outline-secondary ms-1 btn-sm'
              = link_to 'Destroy', group_material, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger ms-1 btn-sm'

app/views/group_materials/new.html.haml
.card.mb-3
  .card-header.d-flex.align-items-center
    %span Add Materials to: #{@group.name}
    = link_to 'Back', edit_group_path(@group), class: 'btn btn-outline-secondary ms-auto'

  #filterOptions.show
    .card-body
      = form_tag request.fullpath , method: :get, class: 'd-flex flex-column px-2' do 
        .row
          .form-group.col-md-4.mb-2
            = label_tag :name, "Material Name:"
            = text_field_tag :name, params[:name], class: 'form-control', placeholder: 'Name'

        .justify-content-between.mt-2
          = submit_tag "Search", class: 'btn btn-primary'
          = link_to "Clear", new_group_material_path(@group), class: 'btn btn-secondary'

.card.mb-2
  %table.table.table-striped.table-hover
    %thead.table-secondary
      %tr
        %th
          Material Name
          = link_to '▲', request.params.merge(sort: 'name', order: 'asc'), class: 'text-decoration-none text-primary'
          = link_to '▼', request.params.merge(sort: 'name', order: 'desc'), class: 'text-decoration-none text-primary'
        %th
          Material Type
          = link_to '▲', request.params.merge(sort: 'material_type', order: 'asc'), class: 'text-decoration-none text-primary'
          = link_to '▼', request.params.merge(sort: 'material_type', order: 'desc'), class: 'text-decoration-none text-primary'
        %th
          Melting Onset
          = link_to '▲', request.params.merge(sort: 'meltingOnset', order: 'asc'), class: 'text-decoration-none text-primary'
          = link_to '▼', request.params.merge(sort: 'meltingOnset', order: 'desc'), class: 'text-decoration-none text-primary'
        %th
          Crystallisation Onset
          = link_to '▲', request.params.merge(sort: 'crystallisationOnset', order: 'asc'), class: 'text-decoration-none text-primary'
          = link_to '▼', request.params.merge(sort: 'crystallisationOnset', order: 'desc'), class: 'text-decoration-none text-primary'
        %th
          Created By
          = link_to '▲', request.params.merge(sort: 'createdBy', order: 'asc'), class: 'text-decoration-none text-primary'
          = link_to '▼', request.params.merge(sort: 'createdBy', order: 'desc'), class: 'text-decoration-none text-primary'
        %th
          Last Modifier
          = link_to '▲', request.params.merge(sort: 'modifiedBy', order: 'asc'), class: 'text-decoration-none text-primary'
          = link_to '▼', request.params.merge(sort: 'modifiedBy', order: 'desc'), class: 'text-decoration-none text-primary'
        %th
          Archived
        %th
    %tbody
      - @group_materials.each do |group_material|
        %tr
          - material = group_material.material
          %td= material.name
          %td= material.material_type
          %td= material.meltingOnset
          %td= material.crystallisationOnset
          %td= material.created_by.email
          %td= material.modified_by.email
          %td= material.archived
          %td
            .btn-toolbar.float-end
              = button_to 'Remove', group_material_path(group_material), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm'
      - @materials.each do |material|
        %tr
          %td= material.name
          %td= material.material_type
          %td= material.meltingOnset
          %td= material.crystallisationOnset
          %td= material.created_by.email
          %td= material.modified_by.email
          %td= material.archived
          %td
            .btn-toolbar.float-end
              = form_with url: group_materials_path, method: :post, scope: :group_material do |form|
                = form.hidden_field :groupId, value: @group.id
                = form.hidden_field :materialId, value: material.id
                = form.submit 'Add', class: 'btn btn-outline-secondary btn-sm'

app/views/group_materials/show.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header
        Group Material details
      .card-body
        %dl.row.mb-0
          %dt.col-md-3 Groupid:
          %dd.col-md-9= @group_material.groupId
          %dt.col-md-3 Materialid:
          %dd.col-md-9= @group_material.materialId
      .card-footer.d-flex
        = link_to 'Edit', edit_group_material_path(@group_material), class: 'btn btn-link'
        = link_to 'Back', group_materials_path, class: 'btn btn-link ms-auto'