config/routes.rb
Rails.application.routes.draw do
  mount EpiCas::Engine, at: '/'
  devise_for :users
  resources :group_cads
  resources :attachment_builds
  resources :group_builds
  resources :group_machines
  resources :attachment_machines
  resources :builds
  resources :machine_parameters
  resources :parameters
  resources :machines do
    get :parameters, on: :member
  end
  resources :build_projects
  resources :group_materials
  resources :materials
  resources :cads
  resources :group_users
  resources :attachments
  resources :groups
  resources :users
  resources :profile

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'cads/:id/download', to: 'cads#download', as: 'download_cad'

  get 'materials/:id/download/:attribute', to: 'materials#download', as: 'download_material' # Defines the root path route ("/")

  get 'builds/id/:id/download', to: 'builds#download', as: 'download_build'

  root 'pages#home'
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id          :bigint           not null, primary key
#  description :string
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Group < ApplicationRecord
  has_many :group_users, class_name: 'GroupUser', foreign_key: 'groupId'
  has_many :users, through: :group_users, source: :user

  has_many :group_materials, foreign_key: 'groupId'
  has_many :materials, through: :group_materials, source: :material
  accepts_nested_attributes_for :group_materials

  has_many :group_cads, foreign_key: 'groupId'
  has_many :cads, through: :group_cads, source: :cad

  has_many :group_builds, foreign_key: 'groupId'
  has_many :builds, through: :group_builds, source: :build

  has_many :group_machines, foreign_key: 'groupId'
  has_many :machines, through: :group_machines, source: :machine

  validates :name, uniqueness: { scope: :id }, presence: true, length: { maximum: 50 }

  def get_group_users
    users
  end

  def get_group_materials
    materials
  end

  def get_group_cads
    cads
  end

  def get_group_builds
    builds
  end

  def get_group_machines
    machines
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  authorize_resource

  # GET /groups
  def index
    @groups = Group.all
  end

  # GET /groups/1
  def show
    @users = @group.get_group_users
    @materials = @group.get_group_materials
    @cads = @group.get_group_cads
    @builds = @group.get_group_builds
    @machines = @group.get_group_machines
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    @users = @group.get_group_users
    @materials = @group.get_group_materials
    @cads = @group.get_group_cads
    @builds = @group.get_group_builds
    @machines = @group.get_group_machines
  end

  # POST /groups
  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /groups/1
  def destroy
    if @group.name == 'Confidential' || @group.name == 'Commercially Available'
      redirect_to groups_url, notice: 'This group cannot be deleted.', status: :forbidden
    else
      @group.destroy
      redirect_to groups_url, notice: 'Group was successfully destroyed.', status: :see_other
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :description)
  end

  # In your controller
  def add_material
    @group = Group.find(params[:group_id])
    @group.materials << Material.find(params[:material_id])
    redirect_to edit_group_path(@group)
  end
end

app/views/groups/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@group) do |f|
  .card-body
    = f.input :name, wrapper_html: { class: 'mb-3' }
    = f.input :description, wrapper_html: { class: 'mb-3' }

  .card-footer.d-flex
    %button.btn.btn-primary{ type: 'submit' }
      Save
    = link_to 'Back', groups_path, class: 'btn btn-link ms-auto'

app/views/groups/edit.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header
        %span Editing Group
      .card-body
        = form_for @group do |f|
          .row
            .form-group.col-md-4.m-2
              %h4 Group Details
          .row
            .form-group.col-md-4.m-2
              = f.label :name, "Name"
          .row
            .form-group.mx-auto
              = f.text_field :name, class: 'form-control rounded'
          .row
            .form-group.col-md-4.m-2
              = f.label :description, "Description"
          .row
            .form-group.mx-auto
              = f.text_area :description, class: 'form-control rounded'
          .row.col-md-4.mx-2.mt-3
            = f.submit class: 'btn btn-primary ml-auto'
      .card-footer
        = link_to 'Back', groups_path, class: 'btn btn-outline-secondary ms-auto'
    .card.mt-3
      .card-header
        %span Group Objects
      .card-body
        .row
          .form-group.m-2
            %h4 Users 
            - if @users.any?
              %ul
                - @users.each do |user|
                  %li= user.email
            - else
              %i.text-muted No users in group
        .row
          .form-group.m-2
            = link_to 'Manage Users', new_group_user_path(@group), class: 'btn btn-outline-primary'
        .row
          .form-group.m-2
            %h4 Builds
            - if @builds.any?
              %ul
                - @builds.each do |build|
                  %li= build.name
            - else
              %i.text-muted No builds in group
        .row
          .form-group.m-2
            = link_to 'Manage Builds', new_group_build_path(@group), class: 'btn btn-outline-primary'
        .row
          .form-group.m-2
            %h4 CADs
            - if @cads.any?
              %ul
                - @cads.each do |cad|
                  %li= cad.name
            - else
              %i.text-muted No CADs in group
        .row
          .form-group.m-2
            = link_to 'Manage CADs', new_group_cad_path(@group), class: 'btn btn-outline-primary'
        .row
          .form-group.m-2
            %h4 Machines
            - if @machines.any?
              %ul
                - @machines.each do |machine|
                  %li= machine.name
            - else
              %i.text-muted No machines in group
        .row
          .form-group.m-2
            = link_to 'Manage Machines', new_group_machine_path(@group), class: 'btn btn-outline-primary'
        .row 
          .form-group.m-2
            %h4 Materials
            - if @materials.any?
              %ul
                - @materials.each do |material|
                  %li= material.name
            - else
              %i.text-muted No materials in group
        .row
          .form-group.m-2
            = link_to 'Manage Materials', new_group_material_path(@group), class: 'btn btn-outline-primary'

app/views/groups/index.html.haml
.card
  .card-header.d-flex.align-items-center
    %span Listing Groups

    = link_to 'New Group', new_group_path, class: 'btn btn-outline-secondary ms-auto'

  %table.table
    %thead
      %tr
        %th Name
        %th Description
        %th
    %tbody
      - @groups.each do |group|
        %tr
          %td= group.name
          %td= group.description
          %td
            .btn-toolbar.float-end
              = link_to 'Show', group, class: 'btn btn-outline-secondary btn-sm'
              = link_to 'Edit', edit_group_path(group), class: 'btn btn-outline-secondary ms-1 btn-sm'
              = link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger ms-1 btn-sm'

app/views/groups/new.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header New Group
      = render 'form'

app/views/groups/show.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header
        Group details
      .card-body
        %dl.row.mb-0
          %dt.col-md-3 Name:
          %dd.col-md-9= @group.name
          %dt.col-md-3 Description:
          %dd.col-md-9= @group.description
      .card-footer.d-flex.justify-content-between.mt-2
        = link_to 'Back', groups_path, class: 'btn btn-outline-secondary'
        = link_to 'Edit', edit_group_path(@group), class: 'btn btn-primary'
    .card.mt-3
      .card-header
        %span Group Objects
      .card-body
        .row
          .form-group.m-2
            %h4 Users 
            - if @users.any?
              %ul
                - @users.each do |user|
                  %li= user.email
            - else
              %i.text-muted No users in group
        .row
          .form-group.m-2
            %h4 Builds
            - if @builds.any?
              %ul
                - @builds.each do |build|
                  %li= build.name
            - else
              %i.text-muted No builds in group
        .row
          .form-group.m-2
            %h4 CADs
            - if @cads.any?
              %ul
                - @cads.each do |cad|
                  %li= cad.name
            - else
              %i.text-muted No CADs in group
        .row
          .form-group.m-2
            %h4 Machines
            - if @machines.any?
              %ul
                - @machines.each do |machine|
                  %li= machine.name
            - else
              %i.text-muted No machines in group
        .row 
          .form-group.m-2
            %h4 Materials
            - if @materials.any?
              %ul
                - @materials.each do |material|
                  %li= material.name
            - else
              %i.text-muted No materials in group