config/routes.rb
Rails.application.routes.draw do
  mount EpiCas::Engine, at: '/'
  devise_for :users
  resources :group_cads
  resources :attachment_builds
  resources :group_builds
  resources :group_machines
  resources :attachment_machines
  resources :builds
  resources :machine_parameters
  resources :parameters
  resources :machines do
    get :parameters, on: :member
  end
  resources :build_projects
  resources :group_materials
  resources :materials
  resources :cads
  resources :group_users
  resources :attachments
  resources :groups
  resources :users
  resources :profile

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'cads/:id/download', to: 'cads#download', as: 'download_cad'

  get 'materials/:id/download/:attribute', to: 'materials#download', as: 'download_material' # Defines the root path route ("/")

  get 'builds/id/:id/download', to: 'builds#download', as: 'download_build'

  root 'pages#home'
end

app/models/machine.rb
# == Schema Information
#
# Table name: machines
#
#  id          :bigint           not null, primary key
#  archived    :boolean
#  createdBy   :integer
#  description :string
#  modifiedBy  :integer
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Foreign Keys
#
#  fk_rails_...  (createdBy => users.id)
#  fk_rails_...  (modifiedBy => users.id)
#
class Machine < ApplicationRecord
  belongs_to :created_by, class_name: 'User', foreign_key: 'createdBy'
  belongs_to :modified_by, class_name: 'User', foreign_key: 'modifiedBy'

  has_many :machine_parameters, foreign_key: 'machineId'
  has_many :parameters, through: :machine_parameters
  has_many :builds, foreign_key: 'buildId'
  has_many :cads, foreign_key: 'machineId'
  has_many :group_machines, foreign_key: 'machineId'

  validates :name, uniqueness: true, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 50 }
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: %i[show edit update destroy]

  authorize_resource

  # GET /machines
  def index
    @machines = get_machines
    @machines = @machines.where('LOWER(name) LIKE ?', "%#{params[:name].downcase}%") if params[:name].present?
  end

  # GET /machines/1
  def show; end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit
    @machine = Machine.find(params[:id])
    @set_params = params[:set_params] if params[:set_params].present?
    @machine_parameters = @machine.machine_parameters
    if params[:name].present?
      @machine_parameters = apply_word_filter(@machine_parameters, :name, params[:name],
                                              machine_parameters: true)
    end

    @parameters = Parameter.all - @machine_parameters.map(&:parameter)
    if params[:name].present?
      @parameters = apply_word_filter(@parameters, :name, params[:name],
                                      machine_parameters: false)
    end
    return unless params[:set_params] == 'true'

    render 'set_parameters'
  end

  # POST /machines
  def create
    @machine = Machine.new(machine_params.merge(created_by: current_user, modified_by: current_user))

    if @machine.save
      redirect_to @machine, notice: 'Machine was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /machines/1
  def update
    if Build.where(machineId: @machine.id).exists? || Cad.where(machineId: @machine.id).exists?
      redirect_to @machine, alert: 'Machine cannot be edited as it is referenced by a build or cad.'
    elsif @machine.update(machine_params.merge(modified_by: current_user))
      redirect_to @machine, notice: 'Machine was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /machines/1
  def destroy
    @machine.destroy
    redirect_to machines_url, notice: 'Machine was successfully destroyed.', status: :see_other
  end

  def parameters
    @machine = Machine.find(params[:id])
    respond_to do |format|
      format.js { render partial: 'parameters', locals: { machine: @machine } }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_machine
    @machine = Machine.find(params[:id])
  end

  def my_group_data
    Machine.joins(:group_machines).where(group_machines: { groupId: current_user.groups.pluck(:id) })
  end

  def my_data
    Machine.where(created_by: current_user.id)
  end

  def commercial_data
    Machine.joins(:group_machines).where(group_machines: { groupId: Group.where(name: 'Commercially Available').first.id })
  end

  def get_machines
    machines = []
    # User can only access data that they have been assigned to.
    machines += my_group_data if current_user.get_role_number >= 0
    # Students can also see data created by them.
    machines += my_data if current_user.get_role_number >= 1
    # Staff gets all commercially available data
    machines += commercial_data if current_user.get_role_number >= 2
    # Admins get all data
    machines = Machine.all if current_user.get_role_number == 3

    Machine.where(id: machines.map(&:id))
  end

  # Only allow a list of trusted parameters through.
  def machine_params
    params.require(:machine).permit(:name, :description, :archived)
  end

  # Applies a word filter to a collection of objects based on a specified attribute and value.
  def apply_word_filter(objects, attribute, value, machine_parameters: false)
    objects.select do |object|
      if machine_parameters
        object.parameter.send(attribute).downcase.include?(value.downcase)
      else
        object.send(attribute).downcase.include?(value.downcase)
      end
    end
  end
end

app/views/machines/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@machine) do |f|
  .card-body
    = f.input :name, wrapper_html: { class: 'mb-3' }
    = f.input :description, wrapper_html: { class: 'mb-3' }
    = f.input :archived, wrapper_html: { class: 'mb-3' }

  .card-footer.d-flex.justify-content-between.mt-2
    = link_to 'Back', @machine, class: 'btn btn-outline-secondary'
    = f.submit 'Submit', class: 'btn btn-primary'

app/views/machines/edit.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    - if @machine.errors.any?
      .col-sm.col-lg 
        .alert.alert-danger 
          %ul
            - @machine.errors.full_messages.each do |message|
              %li= message 
    .card.mb-2
      .card-header Editing Machine
      = render 'form'

app/views/machines/index.html.haml
.card.mb-3
  .card-header.d-flex.align-items-center
    %a{ "data-bs-toggle": "collapse", href: "#filterOptions", class: 'btn btn-outline-secondary' }
      %span Filtering Options ▲▼

  #filterOptions.collapse.show
    .card-body
      = form_tag machines_path, method: :get, class: 'd-flex flex-column px-3' do
        .form-group.mb-2
          = label_tag :name, "Name:"
          = text_field_tag :name, params[:name], class: 'form-control', placeholder: 'Name'
        .d-flex.justify-content-between
          = link_to "Clear Filters", machines_path, class: 'btn btn-secondary'
          = submit_tag "Apply Filters", class: 'btn btn-primary'
.card
  .card-header.d-flex.align-items-center
    %span Listing Machines
    .ms-auto
      = link_to 'New Parameter', new_parameter_path, class: 'btn btn-outline-secondary ms-auto'
      = link_to 'New Machine', new_machine_path, class: 'btn btn-outline-secondary ms-auto'
  %table.table
    %thead
      %tr
        %th Name
        %th Description
        %th Archived
        %th
    %tbody
      - if @machines.empty?
        %tr
          %td{:colspan => 10, :style => "text-align: center; font-weight: bold;"}= "No Machines found"
      - @machines.each do |machine|
        %tr
          %td= machine.name
          %td= machine.description
          %td= machine.archived
          %td
            .btn-toolbar.float-end
              = link_to 'Show', machine, class: 'btn btn-outline-secondary btn-sm'
            .btn-toolbar.float-end.px-2
              = link_to 'Add Parameters', edit_machine_path(machine, set_params: true), class: 'btn btn-outline-danger btn-sm'

app/views/machines/new.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    - if @machine.errors.any?
      .col-sm.col-lg 
        .alert.alert-danger 
          %ul
            - @machine.errors.full_messages.each do |message|
              %li= message 
    .card.mb-2
      .card-header New Machine
      = render 'form'

app/views/machines/set_parameters.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card.mb-3
      .card-header.d-flex.align-items-center
        %span Manage Parameters of: #{@machine.name}
        = link_to 'Done', machines_path, class: 'btn btn-outline-secondary ms-auto'
      #filterOptions.show
        .card-body
          = form_tag request.fullpath, method: :get, class: 'd-flex flex-column px-2' do 
		    .row
              .form-group.col-md-4.mb-2
                = label_tag :name, "Parameter Name:"
                = text_field_tag :name, params[:name], class: 'form-control', placeholder: 'Name'
            .justify-content-between.mt-2
              = submit_tag "Search", class: 'btn btn-primary'
              = link_to "Clear", edit_machine_path(@machine, set_params: true), class: 'btn btn-secondary'
    .card.mb-2
      .card-header.d-flex.align-items-center
        %span Listing Parameters
        = link_to 'New Parameter', new_parameter_path, class: 'btn btn-outline-secondary ms-auto'
      %table.table.table-striped.table-hover
        %thead.table-secondary
          %tr
            %th
              Parameter Name
              = link_to '▲', request.params.merge(sort: 'name', order: 'asc'), class: 'text-decoration-none text-primary'
              = link_to '▼', request.params.merge(sort: 'name', order: 'desc'), class: 'text-decoration-none text-primary'
            %th
              Units
            %th
        %tbody
          - @machine_parameters.each do |param|
            %tr
              - parameter = Parameter.find_by(id: param.parameterId)
              %td= parameter.name
              %td= parameter.unit
              %td
          - @parameters.each do |parameter|
            %tr
              %td= parameter.name
              %td= parameter.unit
              %td
                .btn-toolbar.float-end
                  = form_with url: machine_parameters_path, method: :post, scope: :machine_parameter do |form|
                    = form.hidden_field :machineId, value: @machine.id
                    = form.hidden_field :parameterId, value: parameter.id
                    = form.submit 'Add', class: 'btn btn-outline-secondary btn-sm'

app/views/machines/show.html.haml
.row.justify-content-center
  .col-sm-8.col-lg-6
    .card
      .card-header
        Machine details
      .card-body
        %dl.row.mb-0
          %dt.col-md-3 Name:
          %dd.col-md-9= @machine.name
          %dt.col-md-3 Description:
          %dd.col-md-9= @machine.description
          %dt.col-md-3 Archived:
          %dd.col-md-9= @machine.archived
      .card-footer.d-flex.justify-content-between.mt-2
        = link_to 'Back', machines_path, class: 'btn btn-outline-secondary'
        = link_to 'Edit', edit_machine_path(@machine, set_params: false), class: 'btn btn-primary'